### ISSUE TITLE
How to establish connection?

### ISSUE THREAD

**Issue by dmitry-saritasa** [platinummonkey/mogwai#22]
I'm a little bit confused as to what setup() connects to. 

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.TitanDB.DownloadingAndRunning.html#Tools.TitanDB.DownloadingAndRunning.title

I installed this, I have gremlin server running on port 8182 and dynamodb local on port 4567, but when I issue setup('localhost:8182') and trying to submit code from quickstart example
http://mogwai.readthedocs.io/en/latest/quickstart.html

I get no results at all

```
my_edge = TestEdgeModel.create(outV=my_vertex_1, inV=my_vertex_2, name='my edge')
```

this line never finished. If I connect to dynamodb on localhost:4567 and run the same code, I get this:

```
/home/dmitry/.pyenv/versions/3.5.1/envs/titan/lib/python3.5/site-packages/rexpro/connectors/sync/connection.py in get_response(self)
     74         if bytearray(msg_version)[0] != 1:  # pragma: no cover
     75             # Can only be tested against a known broken version - none known yet.
---> 76             raise exceptions.RexProConnectionException('unsupported protocol version: {}'.format(msg_version))
     77 
     78         serializer_type = self.recv(1)

RexProConnectionException: unsupported protocol version: b'H'

```

I'm using Python 3.5.1 and totally new to **Titan:db**

**Comment by davebshow** [comment]
I believe that you are using Titan 1.0, which uses the Gremlin Server, not Rexster like previous versions of Titan. Therefore, Mogwai will not work for you. I would send you to check out [Goblin](http://goblin.readthedocs.io/en/latest/), because it is a newer OGM/driver for the Gremlin Server, but it doesn't work out of the box with Titan 1.0 because that release uses a really old version of the Gremlin Server that has a lot of deprecated features and is not compatible with newer versions of the TinkerPop stack. If you are interested in Titan, I would look into JanusGraph, as it has been renamed and adopted by the Linux Foundation. For more information in general on the new TinkerPop project, checkout the homepage: http://tinkerpop.apache.org/. If you do want to use the old version of TinkerPop packaged with Titan 1.0. The Goblin driver should work just fine with the GraphSON1MessageSerializer. Unfortunately, the OGM does not work with these early versions of TP.
